# game/story.rpy - generated by tools/build_choices.py
#
# Story flow with the recovered choice menus, branch paths, scenes
# and animations. Choice options and branch jump targets are exact
# (from the decompiled choice and jump-point scripts); branch dialogue
# is selected from the recovered stn() lines by content, since the
# marker -> frame -> handler mapping needs the Director score.

label story_flow:
    call chapter_opening
    # ---- the home arc, structured as the original day chapters
    call chapter_day1
    n "■翌日■"
    call chapter_day2
    n "■数日後■"
    call chapter_day3
    n "■６日後■"
    call chapter_day4
    call overlays_off()
    # ---- choice 1441: father asks about Yurika (converges: iziru101)
    n "妹はどこ行った。"
    menu c1441:
        "知らないよ。今忙しいから後で俺も探してみるよ":
            call reply_dunno
        "ゆりかは外出したよ":
            call reply_out
        "ゆりかとトランプしてるんだ。邪魔しないでよ。":
            call reply_cards
    # ---- choice 554: reply to Yurika (op15 / op50 / op15)
    n "なんだ、今夜はご機嫌ななめか？"
    menu c554:
        "悪かった。実はお前がかわいいと思って…":
            call reply_cute
        "これは男の「美学」だ。エロい疑惑は一切ない！":
            call reply_aesth
        "成長していい身体つきになってきたな。":
            call reply_grown
    # ---- choice 1431: break-in confirm (fn_4|opm_v / cbs8end)
    n "そっと、ゆっくり扉を開けば気づかれなかっただろう"
    menu c1431:
        "YES":
            call breakin_yes
        "NO":
            call breakin_no
    # ---- choice 1175: anniversary gift (ohs10 / ohs20 / ohs30)
    n "照れくさいけど、これさ、結婚記念プレゼント"
    menu c1175:
        "媚薬の効果を親に教え、少量をプレゼントする":
            call ohs10
        "結婚記念に「食事＆ホテル宿泊」をプレゼントする":
            call ohs20
        "俺のコレクション「エロゲー、エロアニメ」を白日の下に晒し、兄妹愛を教育してみる":
            call ohs30
    call chapter_rico_intro
    # ---- choice 69: the route fork (yukai / fera1)
    menu c69:
        "１：りこを誘拐する！":
            call route_kidnap
            # ---- choice 550: kidnapping confirm (yuukai-kihon / start)
            menu c550:
                "YES":
                    call kidnap_go
                    call chapter_confinement
                "NO":
                    call kidnap_stop
                    return
        "２：混乱時に学校へ侵入！":
            call route_school
            call chapter_school
            # ---- choice 900: lick / suck (kf08 / kff08)
            menu c900:
                "舌でぺろぺろしてごらん":
                    call act_lick
                "口にくわえて、しゃぶって":
                    call act_suck
            # ---- choice 1010: rough / gentle (iv5_26 / iv5_25)
            menu c1010:
                "乱暴に強引に":
                    call act_rough
                "優しく誘導しよう":
                    call act_gentle
    call chapter_end
    return

label chapter_opening:
    scene black
    $ renpy.pause(0.6)
    show op_event3 as bgop
    with fade
    window hide
    n "禁断の果物を奪いかけた・・味を知ってしまった。"
    n "決して触れてはいけない。そう分かっていながら、俺は……"
    n "PCからジャックが抜けたヘッドフォンが床に投げ捨てられている"
    window show
    hide bgop
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    n "■これが最近一緒に暮らしだした俺の妹だ■"
    n "■妹といっても父の再婚相手の娘だから血はつながって居ない■"
    n "■最初は人見知りしておどおどしてたんだが、最近は何かと俺に甘えてくる■"
    return

label chapter_day1:
    scene black
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    call scene_010
    call scene_015
    call scene_018
    return

label chapter_day2:
    scene black
    show expression "images/mov2/X_3.jpg" as bg
    with fade
    show ov_day2_head at day2_head_pos
    show ov_grandpa at npc_left
    show ov_brother at npc_right
    call scene_020
    call scene_021
    call scene_025
    call scene_027
    call scene_030
    call scene_034
    return

label chapter_day3:
    scene black
    show expression "images/mov3/1_00000.jpg" as bg
    with fade
    call overlays_on("home")
    show anim_mov3_1 as act
    call scene_037
    call scene_039
    call scene_040
    call scene_042
    call overlays_off()
    return

label chapter_day4:
    scene black
    show expression "images/mov/2_00000.jpg" as bg
    with fade
    call overlays_on("home")
    show anim_mov_2 as act
    call scene_050
    call scene_051
    call scene_052
    call scene_054
    call scene_055
    call scene_060
    call overlays_off()
    return

label chapter_rico_intro:
    hide act
    scene black
    show expression "images/mov3/eki_00000.jpg" as bg
    with fade
    n "あの娘だな。思ってたより随分若いな"
    n "人目に付かない場所となると‥一人で出かける時か、登下校時しかない。"
    n "通学路なら‥４丁目の３つかど辺りがいい。人目につきにくい場所だ。"
    n "年齢も住所も通学路も、個人情報は全て調べつくしたよ。"
    n "誘拐する瞬間さえ他人に目撃されなければ、絶対に俺が犯人だとは分からないはず。"
    n "完全犯罪ができるのか？"
    return

label chapter_end:
    n "俺は幸せだった。"
    n "家庭そして社会の中で、俺たちは普通の兄妹を演じ続けた。"
    n "明日にも、この地域全ての社会システムは崩壊するはずだ。"
    n "災害は起こった。"
    n "俺は獣となり”りこ”という生肉を食らっていた。"
    n "— end of converted scenario —"
    return

# branch reply_dunno: original marker "iziru101"
label reply_dunno:
    hide act
    $ pass  # (original converges immediately: marker iziru101)
    return

# branch reply_out: original marker "iziru101"
label reply_out:
    hide act
    $ pass  # (original converges immediately: marker iziru101)
    return

# branch reply_cards: original marker "iziru101"
label reply_cards:
    hide act
    $ pass  # (original converges immediately: marker iziru101)
    return

# branch reply_cute: original marker "op15"
label reply_cute:
    hide act
    n "お兄ちゃんの嘘つき！"
    n "お兄ちゃんっ、変態趣味を妹に強要しないでよ"
    riko "そうだ。こういう時は素直なのが、身のためだ"
    return

# branch reply_aesth: original marker "op50"
label reply_aesth:
    hide act
    $ pass  # (original converges immediately: marker op50)
    return

# branch reply_grown: original marker "op15"
label reply_grown:
    hide act
    n "でかいおっぱいだ。お前の年齢でここまで発育のいい子は居ないぞ"
    n "ゆりかは発育良すぎだな。お前今何歳なんだよ。"
    n "じゃ、ちょっとだけおっぱい触らせて。"
    return

# branch breakin_yes: original marker "fn_4"
label breakin_yes:
    scene black
    show expression "images/mov/2_00000.jpg" as bg
    with fade
    show anim_mov_3 as act
    passerby_b "変態家宅侵入者を通報しますた！"
    n "【妹部屋の鍵】を使用。ドアの開閉はドアをクリック"
    n "「家宅侵入編"
    n "「鍵がかかってない"
    n "「妹部屋の鍵」GET!"
    n "盗撮って、どんな事するの。"
    n "勝手に部屋に入って、ゆりかのパンツ盗まないでね"
    return

# branch breakin_no: original marker "cbs8end"
label breakin_no:
    hide act
    $ pass  # (original converges immediately: marker cbs8end)
    return

# branch ohs10: original marker "ohs10"
label ohs10:
    scene black
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    show anim_mov_2 as act
    n "媚薬の効果は凄いっ"
    n "できるだけ長い旅行日程で、親父らが好きそうなプランにしないと。"
    n "媚薬を渡した。"
    n "非難したのだろうか？ここ最近近所で人の気配がしない。これは俺に好都合だ。"
    n "数日すれば、俺のチ○ポが恋しくてたまらなくなる"
    return

# branch ohs20: original marker "ohs20"
label ohs20:
    hide act
    scene black
    show expression "images/mov6/fera1HOTEL_00000.jpg" as bg
    with fade
    call overlays_on("hotel")
    n "結婚記念なら親父らも素直に受け取り、外出するはずだ"
    n "両親を前に今夜は一晩中語るぞ。"
    n "照れくさいけど、これさ、結婚記念プレゼント"
    n "温泉旅行なんだよ。ぜひ２人で行ってきてよ"
    mother "そのうち行かせてもらうわ。ありがとうね"
    return

# branch ohs30: original marker "ohs30"
label ohs30:
    scene black
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    show anim_mov_2 as act
    n "エロゲー、エロアニメの中でも特に選りすぐりのは・・これだ！"
    n "「兄妹の禁じられた快楽」俺が神ゲーと崇めるタイトルだ。"
    n "俺のお宝コレクションだよ。集めるのに数年もかかったんだ。"
    n "兄と妹が恋におちて肉体関係へとなだれ込む、超エロエロゲームなんだ"
    return

# branch route_kidnap: original marker "yukai"
label route_kidnap:
    scene black
    show expression "images/mov3/1_00000.jpg" as bg
    with fade
    show anim_mov3_1 as act
    n "誘拐に関する書籍や、犯罪の記事をネットで調べた。"
    n "誘拐の瞬間しか、りこちゃんと接点が無いのだから、その瞬間だけ注意すればいい。"
    n "誘拐場所は？"
    n "誘拐に必要な手錠、催涙スプレー、丈夫なロープなどを準備しないと。"
    n "誘拐の瞬間を絶対に誰もに見られてなかった。マジでうまくいった！"
    n "どうやって、手錠を外したのかは分からない。"
    n "誘拐できたなら、どこかでこっそり監禁しよう。"
    n "監禁場所は、遠い地方の人が来ない寂れた場所がいい。"
    n "四六時中、この女の子の後をつけ、個人情報を集めた。"
    return

# branch route_school: original marker "fera1"
label route_school:
    scene black
    show expression "images/mov2/BG410c.jpg" as bg
    with fade
    show anim_mov2_10 as act
    n "災害後に○学校へ侵入する。"
    n "支援（ボランティア）に来たとでも言えばいい。"
    staff "ボランティアを引き受けてくれるというのは君ですか？"
    staff "大変ありがたい。職員や子供達の保護者にも連絡がつかなくて人手が全く足りてないんでね"
    staff "個人事情などで学校に出てこれる職員がわずか２人なんです"
    staff "私達職員は大変忙しくて、学校に残ってる子供達を見ている暇がないんです"
    staff "子供達は混乱しているので臨時先生になって、見てやって下さい"
    staff "あ、君。野田先生を見なかったかい？"
    n "だが子供達は違った。一部が俺の目を盗み、先生達の戻った職員室へ向かった。"
    return

# branch kidnap_go: original marker "yuukai-kihon"
label kidnap_go:
    scene black
    show expression "images/mov3/1_00000.jpg" as bg
    with fade
    show anim_mov3_10 as act
    n "玄関の扉を開くりこちゃんの横顔を見ながら、俺は路上にひざをついた。"
    n "うまくやれば”事件にさえ”ならない。"
    n "やれる！慎重に行動すれば、世間にも誰にも悟られず、少女誘拐できる。"
    return

# branch kidnap_stop: original marker "start"
label kidnap_stop:
    hide act
    $ pass  # (original converges immediately: marker start)
    return

# branch act_lick: original marker "kf08"
label act_lick:
    scene black
    show expression "images/mov/2_00000.jpg" as bg
    with fade
    show anim_mov_2 as act
    n "ちゃんとなめないと、どうなるか分かってるんだろうな！？"
    n "手をそえるんだ"
    n "じゃ、キャンデーを舐めるように、口に入れるんだ。"
    return

# branch act_suck: original marker "kff08"
label act_suck:
    scene black
    show expression "images/mov/2_00000.jpg" as bg
    with fade
    show anim_mov_2 as act
    n "もっと奥までくわえてごらん。"
    n "そうだ。フェラチオ教えたら、ちゃんと上手に覚えるかな？"
    n "じゃ、口に入れてごらん"
    return

# branch act_rough: original marker "iv5_26"
label act_rough:
    scene black
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    show anim_mov5_00003 as act
    n "その後も、俺は一晩中ゆりかを犯し続けた。"
    n "俺は鬼に取り付かれたように、ゆりかを犯し続けた。"
    n "俺は占領状態の青山○学校で、りこちゃんを犯し続けた。"
    n "りこちゃんを呼びつけては、他の子供達に隠れて犯し続けた。"
    n "それからの俺は乱暴に冷酷にりこちゃんを犯し続けた。"
    return

# branch act_gentle: original marker "iv5_25"
label act_gentle:
    scene black
    show expression "images/mov5/member0012.jpg" as bg
    with fade
    show anim_mov5_00003 as act
    father "一緒に暮らして間がないから仕方ないかもしれないが、妹なんだから優しくしてやるんだぞ"
    father "一緒に暮らして間がないから仕方ないかもしれないが、妹なんだから優しくしてやるんだぞ"
    n "激しいSEXは、時間かけてゆっくり教え込もう。"
    return

# chapter confinement: yukai family
label chapter_confinement:
    call overlays_on("k1")
    scene black
    show expression "images/mov3/1_00000.jpg" as bg
    with fade
    show anim_mov3_1 as act
    n "そして、その美少女を無理やり犯したにも、かかわらず罪に問われないなんて…"
    n "外に逃げられると面倒だな"
    n "生の本番動画は初めて見たんだろう？"
    n "どうやら、俺が他の部屋を探してる時にこっそり外に逃げたようだ"
    n "いつしか俺は自由にりこちゃんという美少女を犯せる快感に我を忘れていた。"
    riko "ここ、どこ・・"
    riko "その鎖は絶対外せないし、誰も君を助けに来ない"
    n "それでいい。大人しくしてろよ"
    riko "お父さんお母さんにお兄さんの事は絶対言いません。ここであった事も秘密にします、約束しますから"
    riko "誘拐されて、命の保障もない状況で勇気あるね"
    riko "自分の置かれた状況が理解できるまで犯して続けてやる！"
    n "誘拐監禁するんだから、鎖でつないで俺の命令に服従させてやる。"
    n "泣いてても、仕方ないだろ"
    riko "もう俺の言いなりなるしかないんだ。残念だが諦めな"
    call overlays_off()
    return

# chapter school: fera1 family
label chapter_school:
    call overlays_on("k1")
    scene black
    show expression "images/mov2/BG410c.jpg" as bg
    with fade
    show anim_mov2_10 as act
    n "りこちゃんは泣いて教室を出て行った"
    n "授業中なんだ、ゆっくりと"
    n "実は前回のテストな。クラスで最下位だったぞ"
    n "そうは思えないな、授業中何を聞いていたんだい"
    n "授業中に、別の事考えてぼんやりしてたんだろう"
    n "おさぼり病を治すために、りこちゃんには厳しい罰が必要だな"
    riko "すみません。こ、今度はテストがんばります"
    n "さぁ罰だ。机に手をついて！"
    n "いいか、りこちゃんの成績が悪いから、罰を与えるんだ"
    staff "早速ですけど、今からお願いできたら助かるんだけど、どうですか？"
    staff "ええ数名。両親と連絡が取れなくて帰宅させたくても出来ないんです"
    staff "では、教室に案内します。子供達の気がまぎれるなら、授業でも何でも構いませんよ"
    n "先生と俺が教室へ入ると、とたんに子供達のおしゃべりが消えた。"
    student "きりーつ。れい。ちゃくせき"
    staff "今日から臨時でみんなを見てくれる○○先生です。先生の言う事をちゃんと聞くように"
    n "俺の簡単な挨拶後、汚れた白衣の教員は”後はよろしく”と言い残し教室から出て行った。"
    n "それから１時間目、２時間目と手作り授業を進めた。"
    n "朝から一向に”あの教員”は俺の授業を見に来ない。"
    riko "ちょっとみんな聞いて。実はこの災害で心の病気になる人が出ている"
    riko "そこで、この時間はみんなの心のケアをする事にした"
    riko "この目隠しをして、手は椅子の後ろで組んで"
    riko "先生が見てるから、ゆっくり深く深呼吸を続けて"
    riko "先生が見てて病気かもしれない子には、少し触れるけど、動かないように我慢してな"
    n "全員がしっかり目隠しするの待ち・・教室のドアをゆっくり開いた。"
    n "教室の子供達は全員大人しくしている。"
    n "教室の子供達も俺の行為を不振がってはいたが、そこままだ○学生。"
    n "～校内放送、望月りこさん、先生のところへ来なさい～"
    n "この前、教室で心の病気の検査したよね。残念だけどりこちゃん病気にかかってるんだ"
    n "でも心配ないよ。先生は治療方法を知ってるから、治療してあげられる"
    riko "どこか痛くなる病気ですか？"
    n "治療しなければ大変な事になるよ。死ぬ人も居るらしい"
    n "変わった病気だから、りこちゃんの為にも秘密にしてあげる。この中で治療しよう。さぁ入って"
    riko "え、これ治療ですか？"
    n "そうだよ。りこちゃんの身体の為なんだ。急いで治療しないとね"
    riko "先生、これ治療じゃないです"
    n "教室でも一人で居る時が多くなっていた。"
    teacher "治療は・・遅すぎた・・。死・・・心から・・・"
    n "大丈夫。学校でも予防注射するだろ。それと同じだよ"
    n "この薬で、今までの１０００倍は気持ち良くなれるからね"
    n "いた！別の教室で掃除をしていた、りこちゃんを見つけた。"
    n "先日のテストの事なんだが、りこちゃんの点数がひどく悪かったんだ"
    n "実は前回のテストな。クラスで最下位だったぞ"
    n "そうは思えないな、授業中何を聞いていたんだい"
    n "授業中に、別の事考えてぼんやりしてたんだろう"
    n "おさぼり病を治すために、りこちゃんには厳しい罰が必要だな"
    riko "すみません。こ、今度はテストがんばります"
    n "さぁ罰だ。机に手をついて！"
    n "いいか、りこちゃんの成績が悪いから、罰を与えるんだ"
    n "そうすれば、お兄ちゃんの病気が良くなるんだよね"
    n "仕方ない！お兄ちゃんの秘密を教えよう。実は病気なんだ。しかもいろんな意味で重病だ"
    n "でも、ゆりかが手伝ってくれるなら、お兄ちゃんの病気は少し良くなるんだ"
    call overlays_off()
    return

